/**
 * High-precision word → topic hints for untagged skeleton lemmas.
 * Used only when CEFR-J tags / POS rules do not decide.
 */
export const LEXICON: Record<string, readonly string[]> = {
  Food: [
    "apple","banana","orange","grape","lemon","lime","peach","pear","berry","strawberry",
    "cherry","mango","melon","watermelon","pineapple","coconut","avocado","tomato","potato",
    "onion","garlic","carrot","cabbage","lettuce","cucumber","pepper","bean","pea","corn",
    "rice","bread","butter","cheese","egg","meat","beef","pork","chicken","fish","salmon",
    "shrimp","crab","soup","salad","sandwich","pizza","burger","pasta","noodle","sauce",
    "salt","sugar","honey","oil","vinegar","flour","cake","cookie","biscuit","pie","dessert",
    "chocolate","candy","ice","cream","yogurt","milk","coffee","tea","juice","water","wine",
    "beer","soda","drink","hungry","thirsty","delicious","tasty","sweet","sour","bitter",
    "spicy","fresh","raw","fried","bake","boil","cook","roast","grill","fry","taste","sip",
    "chew","swallow","bite","menu","recipe","kitchen","breakfast","lunch","dinner","meal",
    "snack","restaurant","cafe","chef","waiter","waitress","customer","order","bill","tip",
    "knife","fork","spoon","plate","bowl","cup","glass","napkin","oven","fridge","freezer",
    "microwave","stove","pan","pot","ingredient","flavor","flavour","calorie","diet","vegetarian",
    "vegan","allergy","nut","seed","herb","spice","jam","toast","cereal","pancake","waffle",
    "steak","sausage","bacon","ham","turkey","lamb","tuna","sushi","curry","stew","soup",
    "broth","dumpling","bagel","muffin","doughnut","donut","pudding","jelly","custard",
  ],
  Health: [
    "doctor","nurse","patient","hospital","clinic","medicine","pill","tablet","syrup","dose",
    "pain","ache","fever","cough","cold","flu","virus","infection","disease","illness","sick",
    "healthy","fit","tired","exhausted","weak","strong","injury","wound","bleed","bruise",
    "bone","blood","heart","lung","liver","stomach","brain","nerve","muscle","skin","tooth",
    "teeth","eye","ear","nose","mouth","throat","neck","shoulder","arm","hand","finger",
    "leg","knee","foot","toe","back","chest","waist","hip","ankle","wrist","headache",
    "toothache","stomachache","allergy","asthma","cancer","diabetes","virus","bacteria",
    "surgery","operation","ambulance","emergency","bandage","cast","crutch","wheelchair",
    "vaccine","injection","prescription","pharmacy","dentist","therapy","recover","heal",
    "symptom","diagnosis","treatment","pregnant","birth","baby","sleep","dream","stress",
    "depress","anxiety","mental","exercise","workout","stretch","breathe","sweat","diet",
    "vitamin","protein","calorie","overweight","slim","obese","addiction","alcohol","smoke",
    "cigarette","drug","poison","allergy","itch","rash","sneeze","vomit","nausea","dizzy",
  ],
  Travel: [
    "travel","trip","journey","tour","vacation","holiday","flight","fly","airport","airline",
    "plane","airplane","pilot","passenger","ticket","passport","visa","border","customs",
    "luggage","baggage","suitcase","backpack","hotel","hostel","motel","inn","resort",
    "reservation","booking","check-in","check-in desk","reception","lobby","elevator",
    "lift","taxi","bus","train","subway","metro","tram","ferry","ship","boat","cruise",
    "car","drive","driver","highway","motorway","road","street","map","direction","route",
    "destination","arrival","departure","delay","cancel","platform","station","terminal",
    "gate","boarding","seat","aisle","window","cabin","crew","guide","tourist","sightseeing",
    "souvenir","currency","exchange","abroad","foreign","local","abroad","island","beach",
    "coast","mountain","valley","desert","jungle","camping","tent","hike","trek","explore",
  ],
  Work: [
    "work","job","career","office","boss","manager","employee","employer","colleague",
    "coworker","staff","team","meeting","deadline","project","task","report","email",
    "salary","wage","pay","bonus","promote","promotion","hire","fire","resign","retire",
    "interview","resume","cv","application","contract","client","customer","business",
    "company","firm","corporation","factory","industry","profession","occupation","shift",
    "overtime","commute","desk","laptop","presentation","schedule","agenda","minute",
    "accountant","engineer","lawyer","doctor","teacher","nurse","chef","waiter","pilot",
    "farmer","driver","builder","architect","designer","developer","programmer","analyst",
    "secretary","assistant","director","executive","ceo","intern","trainee","apprentice",
    "union","strike","negotiate","profit","loss","budget","invoice","tax","finance",
  ],
  School: [
    "school","student","teacher","class","classroom","lesson","homework","exam","test",
    "quiz","grade","score","pass","fail","graduate","university","college","campus",
    "professor","lecture","seminar","course","subject","math","mathematics","science",
    "history","geography","biology","chemistry","physics","literature","grammar","vocabulary",
    "spelling","essay","thesis","research","library","textbook","notebook","pencil","pen",
    "eraser","ruler","blackboard","whiteboard","chalk","degree","diploma","scholarship",
    "tuition","semester","term","curriculum","major","minor","freshman","sophomore",
    "junior","senior","principal","headteacher","dean","tutor","mentor","classmate",
    "study","learn","teach","practice","revise","review","memorize","understand","know",
  ],
  Technology: [
    "computer","laptop","desktop","tablet","phone","smartphone","device","screen","keyboard",
    "mouse","printer","scanner","camera","software","hardware","app","application","program",
    "code","coding","data","database","file","folder","download","upload","install","update",
    "internet","online","offline","website","web","browser","email","password","username",
    "login","logout","account","cloud","server","network","wifi","bluetooth","usb","cable",
    "battery","charge","charger","robot","ai","algorithm","digital","virtual","cyber",
    "hack","virus","malware","security","privacy","pixel","click","tap","swipe","scroll",
    "video","audio","stream","podcast","blog","post","link","url","search","google",
  ],
  Feelings: [
    "happy","sad","angry","mad","upset","glad","pleased","delighted","excited","bored",
    "lonely","nervous","anxious","worried","afraid","scared","terrified","calm","relaxed",
    "stressed","proud","ashamed","embarrassed","jealous","envious","grateful","thankful",
    "hopeful","hopeless","confident","shy","brave","courage","love","hate","like","dislike",
    "miss","care","feel","feeling","emotion","mood","attitude","opinion","believe","doubt",
    "trust","fear","joy","sorrow","grief","pain","pleasure","fun","enjoy","prefer","wish",
    "want","need","hope","dream","surprise","shock","amaze","astonish","disappoint","frustrate",
    "annoy","irritate","satisfy","content","cheerful","miserable","depressed","optimistic",
    "pessimistic","curious","interested","fascinated","impressed","moved","touched","hurt",
  ],
  People: [
    "person","people","man","woman","boy","girl","child","kid","baby","adult","teen",
    "teenager","youth","elder","senior","family","parent","father","mother","dad","mom",
    "mum","brother","sister","son","daughter","uncle","aunt","cousin","nephew","niece",
    "grandfather","grandmother","grandpa","grandma","husband","wife","spouse","partner",
    "friend","buddy","mate","neighbor","neighbour","stranger","guest","host","crowd",
    "audience","citizen","resident","immigrant","refugee","king","queen","prince","princess",
    "marriage","wedding","divorce","engage","date","boyfriend","girlfriend","relative",
    "relationship","society","community","generation","human","individual","someone","somebody",
  ],
  Home: [
    "home","house","apartment","flat","room","bedroom","bathroom","kitchen","living",
    "dining","garage","basement","attic","roof","ceiling","floor","wall","window","door",
    "stairs","hallway","garden","yard","fence","gate","balcony","porch","chimney","brick",
    "furniture","sofa","couch","chair","table","desk","bed","mattress","pillow","blanket",
    "sheet","curtain","carpet","rug","lamp","light","mirror","shelf","drawer","closet",
    "wardrobe","cabinet","sink","toilet","shower","bath","bathtub","towel","soap","clean",
    "dirty","messy","tidy","chore","sweep","mop","vacuum","wash","laundry","iron","dish",
    "rent","landlord","tenant","neighbor","move","unpack","decorate","repair","fix","tool",
  ],
  Shopping: [
    "shop","store","market","mall","supermarket","grocery","buy","sell","purchase","pay",
    "price","cost","cheap","expensive","afford","discount","sale","bargain","deal","offer",
    "money","cash","coin","bill","note","wallet","purse","card","credit","debit","receipt",
    "change","refund","exchange","return","cart","basket","shelf","aisle","brand","label",
    "product","goods","item","customer","cashier","checkout","queue","line","order","delivery",
    "package","box","bag","gift","present","tax","tip","budget","save","spend","earn","owe",
    "debt","loan","bank","account","atm","cashpoint","invest","profit","loss","rich","poor",
  ],
  Nature: [
    "nature","natural","environment","weather","climate","sun","moon","star","sky","cloud",
    "rain","snow","wind","storm","thunder","lightning","fog","mist","hot","cold","warm",
    "cool","humid","dry","temperature","season","spring","summer","autumn","fall","winter",
    "tree","forest","wood","jungle","flower","plant","grass","leaf","root","seed","fruit",
    "animal","bird","fish","insect","dog","cat","horse","cow","pig","sheep","chicken",
    "lion","tiger","bear","wolf","deer","elephant","monkey","snake","frog","bee","butterfly",
    "river","lake","ocean","sea","wave","beach","island","mountain","hill","valley","desert",
    "rock","stone","soil","earth","planet","pollution","recycle","wildlife","habitat","species",
    "volcano","earthquake","flood","drought","fire","ice","glacier","cave","waterfall",
  ],
  Sports: [
    "sport","sports","game","play","player","team","match","score","win","lose","draw",
    "champion","trophy","coach","train","practice","athlete","olympic","race","run","jog",
    "walk","swim","swim","dive","surf","ski","snowboard","skate","cycle","bike","climb",
    "hike","camp","fish","hunt","golf","tennis","soccer","football","basketball","baseball",
    "volleyball","hockey","cricket","rugby","boxing","wrestling","martial","yoga","gym",
    "fitness","hobby","leisure","fun","puzzle","chess","card","board","toy","doll","kite",
    "ball","bat","racket","goal","net","field","court","stadium","arena","fan","cheer",
    "ballet","dance","sing","music","instrument","guitar","piano","drum","hobby","pastime",
  ],
  Media: [
    "media","news","newspaper","magazine","article","headline","journalist","reporter",
    "editor","column","columnist","tv","television","radio","channel","broadcast","show",
    "program","series","episode","film","movie","cinema","actor","actress","director",
    "scene","script","audience","celebrity","star","fame","famous","book","novel","story",
    "poem","poetry","author","writer","reader","publish","publisher","library","bookstore",
    "music","song","singer","band","album","concert","opera","theater","theatre","drama",
    "comedy","tragedy","cartoon","anime","comic","photograph","photo","camera","video",
    "youtube","podcast","blog","influencer","stream","netflix","dvd","cd","record","hit",
  ],
  Society: [
    "society","social","community","culture","tradition","custom","ceremony","festival",
    "holiday","government","politics","political","president","minister","parliament",
    "congress","election","vote","democracy","law","legal","illegal","court","judge",
    "jury","lawyer","crime","criminal","theft","steal","rob","murder","police","prison",
    "jail","gaol","punish","fine","tax","citizen","nation","national","country","state",
    "city","town","village","capital","embassy","passport","war","peace","army","soldier",
    "weapon","gun","bomb","violence","justice","right","freedom","equality","religion",
    "church","temple","mosque","god","pray","faith","charity","volunteer","protest","riot",
  ],
  Communication: [
    "speak","talk","say","tell","ask","answer","reply","respond","discuss","argue",
    "explain","describe","mention","suggest","advise","warn","promise","refuse","agree",
    "disagree","conversation","dialogue","chat","gossip","rumor","rumour","message","letter",
    "note","postcard","email","text","call","phone","ring","listen","hear","voice","sound",
    "loud","quiet","whisper","shout","scream","language","word","sentence","phrase","meaning",
    "translate","interpret","sign","signal","gesture","nod","wave","smile","laugh","cry",
    "write","read","print","publish","announce","declare","inform","notify","contact",
    "communicate","expression","accent","pronounce","pronunciation","fluent","native",
  ],
  Appearance: [
    "appear","appearance","look","looks","seem","beautiful","pretty","handsome","ugly",
    "attractive","cute","gorgeous","plain","fancy","style","fashion","clothes","clothing",
    "wear","dress","shirt","t-shirt","pants","trousers","jeans","skirt","shorts","suit",
    "jacket","coat","sweater","sweatshirt","hoodie","hat","cap","scarf","glove","sock",
    "shoe","boot","sandal","tie","belt","button","zipper","pocket","sleeve","collar",
    "uniform","costume","jewelry","jewellery","ring","necklace","earring","bracelet","watch",
    "hair","beard","mustache","moustache","bald","blonde","brunette","tall","short","thin",
    "fat","slim","muscular","fit","skin","pale","tan","wrinkle","scar","makeup","perfume",
    "personality","character","kind","mean","friendly","polite","rude","honest","lazy",
    "hardworking","clever","smart","stupid","wise","funny","serious","quiet","loud","shy",
  ],
  "Daily life": [
    "day","night","morning","afternoon","evening","midnight","noon","today","tomorrow",
    "yesterday","week","month","year","time","hour","minute","second","clock","watch",
    "early","late","soon","always","never","often","sometimes","usually","already","still",
    "yet","again","once","twice","daily","routine","habit","life","live","alive","dead",
    "begin","start","finish","end","stop","continue","wait","stay","leave","arrive","come",
    "go","get","put","take","give","make","do","use","try","keep","hold","open","close",
    "bring","carry","send","receive","find","lose","search","choose","decide","change",
    "happen","seem","become","remain","include","contain","need","want","help","allow",
    "let","ask","thing","stuff","way","place","part","side","end","kind","sort","type",
    "number","amount","lot","bit","piece","example","idea","fact","problem","question",
    "answer","reason","cause","result","effect","difference","same","other","another",
    "new","old","young","good","bad","great","small","large","big","long","short","high",
    "low","right","wrong","true","false","real","possible","important","necessary","easy",
    "difficult","hard","simple","special","general","common","normal","usual","ready",
    "busy","free","full","empty","open","closed","available","sure","clear","certain",
  ],
  "Grammar words": [
    "however","therefore","moreover","furthermore","nevertheless","nonetheless","meanwhile",
    "otherwise","instead","besides","although","though","unless","whether","whereas",
    "thereby","hence","thus","indeed","anyway","anyhow","alike","ago","apart","aside",
  ],
};

/** Build reverse map word → topic (first listed topic wins if duplicates). */
export function buildLexiconIndex(): Map<string, string> {
  const map = new Map<string, string>();
  for (const [topic, words] of Object.entries(LEXICON)) {
    for (const w of words) {
      const key = w.toLowerCase();
      if (!map.has(key)) map.set(key, topic);
    }
  }
  return map;
}
